In [ ]:
import numpy as n
A= n.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A1= n.linspace(1,7,6).reshape(2,3)
print(A1)

[[1.  2.2 3.4]
 [4.6 5.8 7. ]]


In [ ]:
A2=n.array([1,2,3,4,5,6]).reshape(3,2)
print(A2)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
A3=n.array([1,2,3,4,5,6])
A3.resize(2,3) #changes the shape of original array
#reshape - changes needs saving in another variable
print(A3)

In [ ]:
A = n.array([34,56,78,90])
B= n.array([7,9,3,12])  #Array will throw an error while arrays iterate themselves
c=A-B
print(A-B)

[27 47 75 78]


In [ ]:
A=n.array([34,56,78,90]).reshape(2,2)
B=n.array([7,9,3,12]).reshape(2,2)
print(A)
print("----------------")
print(B)
print("----------------")
c=A*B          #one on one  multiplication
print(c)

[[34 56]
 [78 90]]
----------------
[[ 7  9]
 [ 3 12]]
----------------
[[ 238  504]
 [ 234 1080]]


In [ ]:
A=n.array([34,56,78,90]).reshape(2,2)
B=n.array([7,9,3,12]).reshape(2,2)
print(A)
print("----------------")
print(B)
print("----------------")
c=A@B          #matrix  multiplication
print(c)

[[34 56]
 [78 90]]
----------------
[[ 7  9]
 [ 3 12]]
----------------
[[ 406  978]
 [ 816 1782]]


In [ ]:
A=n.array([34,56,78,90]).reshape(2,2)
B=n.array([7,9,3,12]).reshape(2,2)
print(A)
print("----------------")
print(B)
print("----------------")
c=A.dot(B)          #matrix multiplication
print(c)

[[34 56]
 [78 90]]
----------------
[[ 7  9]
 [ 3 12]]
----------------
[[ 406  978]
 [ 816 1782]]


In [ ]:
A= n. array([1,2,3,4])
print("maximum : ",A.max())    #max and min functions supports numeric data types
print("minimum : ",A.min())

maximum :  4
minimum :  1


In [ ]:
A= n.array([34,56,78,90]).reshape(2,2)
print(A)
print("----------------")
print(A.max(axis=0))    #axis=0  -column
print("----------------")
print(A.min(axis=1))    #axis=1  -row

[[34 56]
 [78 90]]
----------------
[78 90]
----------------
[34 78]


In [ ]:
#joining arrays
A = n.array([34,56,78,90]).reshape(2,2)
B = n.array([7,9,3,12]).reshape(2,2)
print(A)
print("-------------")
print(B)
print("-------------")
print("After vertically stacking the arrays")
print(n.stack((A,B),axis=0))
print("--------------")
print(n.stack((A,B),axis=1))

[[34 56]
 [78 90]]
-------------
[[ 7  9]
 [ 3 12]]
-------------
After vertically stacking the arrays
[[[34 56]
  [78 90]]

 [[ 7  9]
  [ 3 12]]]
--------------
[[[34 56]
  [ 7  9]]

 [[78 90]
  [ 3 12]]]


In [ ]:
A=n.arange(30).reshape(2,3,5)  #(g,r,c)
print(A)
print("After dstack")
print(n.dstack(A))  #no of rows --> no of groups
#no of col in every group --> no.of rows in every group

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
A = n.arange(18).reshape(6,3)
print(A)
print("After splitting")
n.vsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays
A = n.arange(18).reshape(6,3)
print(A)
print("After splitting")
n.vsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays
A = n.arange(18).reshape(6,3)
print(A)
print("After splitting")
n.hsplit(A,3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[ 0],
        [ 3],
        [ 6],
        [ 9],
        [12],
        [15]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]])]

In [ ]:
#splitting arrays
A = n.arange(36).reshape(6,6)
print(A)
print("After splitting")
n.hsplit(A,(3,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
After splitting


[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]])]

In [ ]:
A = n.arange(16).reshape(8,2)
print(A)
print(A.argmax(axis =0))
print(A.argmax(axis =1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[7 7]
[1 1 1 1 1 1 1 1]


In [ ]:
A = n.arange(16).reshape(8,2)
print(A)
print(A.argmin(axis =0))
print(A.argmin(axis =1))

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[0 0]
[0 0 0 0 0 0 0 0]


Statistics

In [ ]:
#mean,median,std,var
A= n.array([12,34,25,66,71,88])
print("Mean: ",n.mean(A))
print('Median: ',n.median(A))
print('Variance',n.var(A))
print("standard Deviation: ",n.std(A))

Mean:  49.333333333333336
Median:  50.0
Variance 743.888888888889
standard Deviation:  27.274326552435515


Trigonometry

In [ ]:
A=n.pi
print(A)
print(n.rad2deg(A))

3.141592653589793
180.0


In [ ]:
A=n.array([n.pi/4,n.pi/3,n.pi/2,n.pi])
print("In radians : ",A)
print("In degrees: ",n.rad2deg(A))

In radians :  [0.78539816 1.04719755 1.57079633 3.14159265]
In degrees:  [ 45.  60.  90. 180.]


In [ ]:
C=n.array([0,30,45,60,90,120,180])
print(n.deg2rad(C))

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
print(n.sin(C))
print(n.cos(C))
print(n.tan(C))
print(n.arctan(C))
print(n.arcsin(C))
print(n.arccos(C))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118
 -0.80115264]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097
 -0.59846007]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301
  1.33869021]
[0.         1.53747533 1.54857776 1.5541312  1.55968567 1.56246319
 1.56524083]
[ 0. nan nan nan nan nan nan]
[1.57079633        nan        nan        nan        nan        nan
        nan]


<ipython-input-57-a544f9e8e062>:5: RuntimeWarning: invalid value encountered in arcsin
  print(n.arcsin(C))
<ipython-input-57-a544f9e8e062>:6: RuntimeWarning: invalid value encountered in arccos
  print(n.arccos(C))


In [ ]:
#searching

A=n.array([90,3,45,21,34,90,21])
print(n.where(A%2==0))
print(n.where(A==90))
print(n.where(A>25))


(array([0, 4, 5]),)
(array([0, 5]),)
(array([0, 2, 4, 5]),)


In [ ]:
#read an array with one dimension
import numpy as n
A=n.array([1,2,3,4])
print(n.searchsorted(A,4))

3


In [ ]:
A = n.array([6,24,60,12,18])
B=  n.array([3,1,5,9,4])
print(n.add(A,B))
print(n.subtract(A,B))
print(n.divide(A,B))
print(n.mod(A,B))

[ 9 25 65 21 22]
[ 3 23 55  3 14]
[ 2.         24.         12.          1.33333333  4.5       ]
[0 0 0 3 2]


Sort

In [ ]:
A=n.array([6,24,60,12,18])
print(n.sort(A))

[ 6 12 18 24 60]


In [ ]:
A=n.array([6,24,60,12,18])
B=n.array([6,4,10,5,4])
print(n.union1d(A,B))
print(n.setdiff1d(A,B))
print(n.intersect1d(A,B))

[ 4  5  6 10 12 18 24 60]
[12 18 24 60]
[6]


In [ ]:
import numpy as n
print(n.around(3.16626,4))
print(n.trunc([-3.1666,3.6666]))
print(n.fix([-3.1666,3.6666]))
print(n.floor([-3.1666,3.6666]))
print(n.ceil([-3.1666,3.1]))

3.1663
[-3.  3.]
[-3.  3.]
[-4.  3.]
[-3.  4.]


More functions

In [ ]:
A=n.array([3,4,16,19,10])
print(n.cumsum(A))   #cumulative sum
print(n.cumprod(A))   #cumulative product


[ 3  7 23 42 52]
[    3    12   192  3648 36480]


In [ ]:
print(n.lcm(45,65))
print(n.gcd(445,655))

585
5


In [ ]:
Ar=n.array([45,65,30])
print(n.lcm.reduce(Ar))

1170


In [ ]:
a=n.array([[1,2],[3,4]])
print(n.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
from numpy import random as rd
A= rd.rand()   #default limit o to 0.99
B=rd.rand(10)     #default limit 0 to 0.99 and prints 10 random numbers
print(A)
print(B)

0.7334583416486201
[0.32360839 0.08288264 0.89712451 0.39536254 0.34486095 0.17196042
 0.27190279 0.82756522 0.38714107 0.44945759]


In [ ]:
A=rd.randint(4)
print(A)

0


In [ ]:
A=rd.randint(50,size=6)   #limit
B=rd.randint(50,size=(2,3))
print(A)
print("--------------------")
print(B)

[33 29 25  6 39 24]
--------------------
[[16  1 40]
 [10 46 49]]


In [ ]:
A=n.array([1,2,3])
b=n.array([4,5,6])
print(n.inner(A,b))   #1x4 + 2x5 + 3x6

32


In [ ]:
A=n.array([1,2,3])
b=n.array([4,5,6])
print(n.outer(A,b))    #1x(4,5,6)  #2x(4,5,6)   #3x(4,5,6)
print("----------------")
print(n.cross(A,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
----------------
[-3  6 -3]
