In [ ]:
#sample
a=10
print("I am ",a," years old");

I am  10  years old


In [1]:
# arithmetic
a=int(input("enter a number"));
b=int(input("enter another number"));
c = (a+b);
print("addition :",c);
print("difference : ",a-b);
print("product : ",a*b)
print("quotient :",a/b)
print("remainder :",a%b);
print("power is ",a**b);

enter a number12
enter another number25
addition : 37
difference :  -13
product :  300
quotient : 0.48
remainder : 12
power is  953962166440690129601298432


In [ ]:
#problem : take a number from user(salary).if the salary is more than 50k there is a 10% tax print his final salary
a=int(input("enter your salary:"))
if (a>=50000):
  a=a-a*(0.1);
  print("salary after tax deduction :",a)

else:
  print("your salary is less than 50000 , hence no tax salary deduction")



enter your salary:40000
your salary is less than 50000 , hence no tax salary deduction


In [ ]:
#get the salary from the user if the salary is more than equal to 50k apply 10% tax deduction if the salary is less than 50k apply 5% tax if the salary is more than 70 K apply 12 % tax if salary more than 1lackh print your promoted to next level
a=int(input("enter your salary:"))
if (a>=100000):
  print("you are promoted")
elif(a>=70000):
  print("12% tax deducted , salary :",a-a*(0.12))
elif(a>=51000):
  print("12% tax deducted , salary :",a-a*(0.10))
else:
  print("12% tax deducted , salary :",a-a*(0.5))


enter your salary:100000
you are promoted


In [ ]:
#printing multiplicaton table

num=int(input("Enter a number"))
for i in range(1, 11,1):
   print(num, 'x', i, '=', num*i)m

Enter a number125
125 x 1 = 125
125 x 2 = 250
125 x 3 = 375
125 x 4 = 500
125 x 5 = 625
125 x 6 = 750
125 x 7 = 875
125 x 8 = 1000
125 x 9 = 1125
125 x 10 = 1250


In [ ]:
a=int(input("Enter a number : "))
i=1
while(i<=10):
  print(a," X ",i," = ",a*i)
  i=i+1

Enter a number : 125
125  X  1  =  125
125  X  2  =  250
125  X  3  =  375
125  X  4  =  500
125  X  5  =  625
125  X  6  =  750
125  X  7  =  875
125  X  8  =  1000
125  X  9  =  1125
125  X  10  =  1250


In [ ]:
#list heterogeneous
l = [1,"hi",3,"hello",5]
for i in l :
  print(i)

1
hi
3
hello
5


In [ ]:
#append
l.append("last")
for i in l :
  print(i)


1
hi
3
hello
5
last


In [ ]:
#insert
l.insert(3,"inserted")
for i in l :
  print(i)

1
hi
3
inserted
hello
5
last


In [3]:
#extend
m=[6,"bye",7]
l.extend(m)



NameError: name 'l' is not defined

In [ ]:
for i in l:
  print(i)

1
hi
3
inserted
hello
5
last
6
bye
7


In [ ]:
#remove
ml.remove(6)

In [ ]:
for i in l:
  print(i)

1
hi
3
inserted
hello
5
last
bye
7


In [ ]:
#pop
l.pop(-2)
for i in l:
  print(i)

1
hi
3
inserted
hello
5
last
7


In [ ]:
print(l)

[1, 'hi', 3, 'inserted', 'hello', 5, 'last', 7]


In [ ]:
l.clear()

In [ ]:
print(l)

[]


In [ ]:
m.clear()
print(m)

[]


In [ ]:
#create a list of integers (10 elements) print there squares
#save this square in a new list
l = [1,3,5,7,9,2,4,6,8,10]
#m=[]
m=[ i*i for i in l]
#for i in l:
#  m.append(i*i)
print(m)


[1, 9, 25, 49, 81, 4, 16, 36, 64, 100]


In [ ]:
m9=[i*i for i in l if i>5]
print(m9)


[49, 81, 36, 64, 100]


In [ ]:
l1=[23,67,12,34,69]
res=[i*i if i>50 else 'X' for i in l1]
print(res)

['X', 4489, 'X', 'X', 4761]


In [ ]:
#take salary feom the user if salary is less than 50 k 10% tax other wise 15% tax
a=[780000,50400,34000,23000,14000]
b=[(i-i*0.1) if i<50000 else (i-i*0.15) for i in a  ]
print(b)

[663000.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#dictionary
dict1={1:'tarun',2:'sriram',3:'satish'}
print(dict1)

{1: 'tarun', 2: 'sriram', 3: 'satish'}


In [ ]:
print(dict1.keys())
print(dict1.values())

dict_keys([1, 2, 3])
dict_values(['tarun', 'sriram', 'satish'])


In [ ]:
print(dict1[1])

tarun


In [ ]:
dict2={'dept':'CSE',"details":{"year":"2","sec":"D","Count":71}}
print("year is ",dict2['details']['year'])
print("section : ",dict2['details']['sec'])
print("count : ",dict2['details']['Count'])

year is  2
section :  D
count :  71


In [ ]:
list=[1,2]
lis=['hi','hello']
new=(zip(list,lis))
print(dict(new))

{1: 'hi', 2: 'hello'}


In [ ]:
#numpy
import numpy as n
A=n.array([1,2,3,4])  #1darray
print(A.ndim)
print(A.shape)


1
(4,)


In [ ]:
import numpy as n
A1=n.array([[1,2,3],[4,5,6],[7,8,9]])   #2d array
#elements in each row = columns
print(A1)
print(A1.ndim)
print(A1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [ ]:
import numpy as n
A2=n.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])   #3d array
#elements in each row = columns
print(A2)
print(A2.ndim)
print(A2.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
3
(2, 3, 3)


In [ ]:
A2 = n.ones((2,4,3))
print(A2)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
A2 = n.zeros((2,4,3))
print(A2)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A3= n.eye(4)
print(A3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A4=n.arange(1,10,2)
print(A4)
print(type(A4))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using a range function b/w 1 and 1000
A5=n.arange(8,1001,8)
print(A5)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [6]:
import numpy as n
A6=n.linspace(12,25,8)  #splitting a range into n numbers with common differences
print(A6)

[12.         13.85714286 15.71428571 17.57142857 19.42857143 21.28571429
 23.14285714 25.        ]


#tuples,set
#documentation
#qrcode
